runtime: python39
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3.9

env_variables:
  # Agrega otras variables de entorno según sea necesario
  GOOGLE_CLOUD_PROJECT: technical-test-404920
